services:
  - type: web
    name: viota
    runtime: static
    buildCommand: pnpm install && pnpm --filter @viota/client build
    staticPublishPath: packages/client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
