/**
 * Generates `test/fixtures/token-contract.json` (A7 — the token-fixture
 * contract). Run from `packages/worker/`:
 *
 *   npx vite-node scripts/generate-token-contract.ts
 *
 * This is a MANUAL, occasional operation (not run on every test — the JSON it
 * produces is checked in and consumed verbatim by `test/token-contract.test.ts`,
 * and — per A7/Step 3 — will be copied verbatim into the hub repo, whose
 * identity-service tests then regenerate/validate it there too). Re-run it
 * ONLY when a deliberate, coordinated JWT claim-shape change happens on BOTH
 * sides — that is the whole point of the fixture: a claim shape drift on
 * either side fails a test instead of silently breaking token
 * interoperability between viota-worker/vgames-identity and vjaipur/vwiki.
 *
 * Goes through the REAL signing code (`signToken`/`signVGamesToken` in
 * `../src/jwt.ts`) for every fixture EXCEPT the admin token (there is no
 * player-facing endpoint that mints one — `identity/admin.ts` only verifies;
 * admin tokens are minted out-of-band, so this script mints it directly via
 * `jose`, mirroring `identity/admin.ts`'s ADMIN_ISS/ADMIN_AUD/HS256 exactly).
 *
 * TEST-ONLY secrets below. Never deploy these values or reuse them for
 * anything real — they exist only so a checked-in JSON fixture and the tests
 * that consume it can both derive the same tokens deterministically.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { SignJWT } from 'jose'
import { signToken, signVGamesToken } from '../src/jwt'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_PATH = join(HERE, '..', 'test', 'fixtures', 'token-contract.json')

// Fixed anchor time for every "valid" fixture's iat, so regenerating the
// fixture without a deliberate code change reproduces byte-identical tokens.
const ANCHOR_MS = Date.UTC(2026, 0, 1) // 2026-01-01T00:00:00Z
// 100 years — long enough that this fixture never self-expires across its
// checked-in lifetime (incl. after the Step-3 copy into the hub).
const LONG_TTL_SECONDS = 100 * 365 * 24 * 60 * 60
// Far enough in the past that this is ALWAYS expired relative to any
// realistic "now" the test suite runs at.
const PAST_MS = Date.UTC(2020, 0, 1)

const SECRET = 'fixture-test-only-player-secret-0123456789ab'
const ADMIN_SECRET = 'fixture-test-only-admin-secret-0123456789ab'

const LEGACY_ACCOUNT_ID = 'fixture-legacy-account-0001'
const VGAMES_ACCOUNT_ID = 'fixture-vgames-account-0002'
const ADMIN_SUBJECT = 'fixture-admin-operator-0003'

async function main() {
  const legacyViota = await signToken(LEGACY_ACCOUNT_ID, SECRET, ANCHOR_MS, LONG_TTL_SECONDS)

  const vgamesEpoch = await signVGamesToken(
    { accountId: VGAMES_ACCOUNT_ID, status: 'claimed', epoch: 3 },
    SECRET,
    { now: ANCHOR_MS, ttlSeconds: LONG_TTL_SECONDS },
  )

  // Legacy-shaped claims, iat/exp both far in the past.
  const expired = await signToken(LEGACY_ACCOUNT_ID, SECRET, PAST_MS)

  // vgames-shaped claims, otherwise valid, but signed for an audience NEITHER
  // verifyToken (expects viota-web) NOR verifyAnyToken (expects vgames-web OR
  // viota-web) accepts.
  const wrongAud = await signVGamesToken(
    { accountId: VGAMES_ACCOUNT_ID, status: 'claimed', epoch: 0 },
    SECRET,
    { now: ANCHOR_MS, ttlSeconds: LONG_TTL_SECONDS, aud: 'some-other-service-web' },
  )

  // Admin step-up token — mirrors identity/admin.ts's verifyAdminToken
  // expectations exactly (iss='vgames', aud='vgames-admin', HS256, a non-empty
  // string `sub`). No app-code sign helper exists for this (minted out-of-band
  // in real ops), so it's built directly here.
  const admin = await new SignJWT({})
    .setProtectedHeader({ alg: 'HS256' })
    .setSubject(ADMIN_SUBJECT)
    .setIssuer('vgames')
    .setAudience('vgames-admin')
    .setIssuedAt(Math.floor(ANCHOR_MS / 1000))
    .setExpirationTime(Math.floor(ANCHOR_MS / 1000) + LONG_TTL_SECONDS)
    .sign(new TextEncoder().encode(ADMIN_SECRET))

  const fixture = {
    $comment:
      'GENERATED by scripts/generate-token-contract.ts — do not hand-edit. ' +
      'TEST-ONLY secrets/tokens (never real credentials). Consumed by ' +
      'test/token-contract.test.ts. Step 3 copies this file verbatim into the ' +
      'hub repo; regenerate only for a deliberate, coordinated claim-shape change.',
    secret: SECRET,
    adminSecret: ADMIN_SECRET,
    fixtures: {
      legacyViota: {
        description: 'A legacy viota token (iss=viota, aud=viota-web, no epoch claim) — the shape /auth/quick has always minted.',
        token: legacyViota,
        accountId: LEGACY_ACCOUNT_ID,
        expect: { verifyToken: 'valid', verifyAnyToken: 'valid', verifyAdminToken: 'invalid' },
      },
      vgamesEpoch: {
        description: 'A vgames token (iss=vgames, aud=vgames-web, carries epoch+status) — the shape /auth/login mints.',
        token: vgamesEpoch,
        accountId: VGAMES_ACCOUNT_ID,
        epoch: 3,
        status: 'claimed',
        expect: { verifyToken: 'invalid', verifyAnyToken: 'valid', verifyAdminToken: 'invalid' },
      },
      expired: {
        description: 'A legacy-shaped token whose iat/exp are both far in the past.',
        token: expired,
        accountId: LEGACY_ACCOUNT_ID,
        expect: { verifyToken: 'invalid', verifyAnyToken: 'invalid', verifyAdminToken: 'invalid' },
      },
      wrongAud: {
        description: 'vgames-shaped claims, but signed for an audience neither verifyToken nor verifyAnyToken accept.',
        token: wrongAud,
        accountId: VGAMES_ACCOUNT_ID,
        expect: { verifyToken: 'invalid', verifyAnyToken: 'invalid', verifyAdminToken: 'invalid' },
      },
      admin: {
        description: 'An admin step-up token (iss=vgames, aud=vgames-admin), signed with adminSecret — gates POST /admin/merge and GET /admin/merge-audit.',
        token: admin,
        subject: ADMIN_SUBJECT,
        expect: { verifyToken: 'invalid', verifyAnyToken: 'invalid', verifyAdminToken: 'valid' },
      },
    },
  }

  writeFileSync(OUT_PATH, JSON.stringify(fixture, null, 2) + '\n')
  console.log(`wrote ${OUT_PATH}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
